# Generated by Django 5.2.17 on 2026-08-23 11:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('credit_card', 'クレジットカード'), ('code_payment', 'コード決済'), ('point', 'ポイント'), ('bank', '銀行'), ('cash', '現金・その他')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='code_payments', to='ledger.paymentsource')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_on', models.DateField()),
                ('shop_name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('amount_yen', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('payment_source_name_snapshot', models.CharField(max_length=100)),
                ('payment_source_kind_snapshot', models.CharField(max_length=20)),
                ('linked_source_name_snapshot', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('linked_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funded_entries', to='ledger.paymentsource')),
                ('payment_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.paymentsource')),
            ],
            options={
                'ordering': ['-spent_on', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_year', models.PositiveSmallIntegerField()),
                ('provider_name', models.CharField(max_length=150)),
                ('paid_amount_yen', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cumulative_amount_yen', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_entries', to='ledger.person')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentsource',
            constraint=models.UniqueConstraint(fields=('kind', 'name'), name='unique_source_name_per_kind'),
        ),
    ]
