# Generated by Django 5.2.17 on 2026-08-23
import django.db.models.deletion
from datetime import date

from django.db import migrations, models


def group_existing_medical_entries(apps, schema_editor):
    """Make every legacy row a safe one-detail visit without guessing relations."""
    MedicalEntry = apps.get_model("ledger", "MedicalEntry")
    MedicalVisit = apps.get_model("ledger", "MedicalVisit")
    db_alias = schema_editor.connection.alias
    entries = MedicalEntry.objects.using(db_alias).all().order_by("person_id", "record_year", "created_at", "id")
    running_by_person_year = {}
    for entry in entries.iterator():
        # Before this migration there was no visit date or relation.  January 1
        # of the recorded year preserves the selected-year context without
        # inventing a real treatment date.  Pharmacy/transport rows deliberately
        # get no hospital name because their parent hospital cannot be inferred.
        visit = MedicalVisit.objects.using(db_alias).create(
            person_id=entry.person_id,
            record_year=entry.record_year,
            visited_on=date(entry.record_year, 1, 1),
            hospital_name=entry.provider_name if entry.category == "hospital" else "",
            deleted_at=entry.deleted_at,
        )
        MedicalVisit.objects.using(db_alias).filter(pk=visit.pk).update(
            created_at=entry.created_at,
            updated_at=entry.updated_at,
        )
        MedicalEntry.objects.using(db_alias).filter(pk=entry.pk).update(visit_id=visit.pk)
        if entry.deleted_at is None:
            key = (entry.person_id, entry.record_year)
            running_by_person_year[key] = running_by_person_year.get(key, 0) + entry.paid_amount_yen
            MedicalVisit.objects.using(db_alias).filter(pk=visit.pk).update(
                cumulative_amount_yen=running_by_person_year[key],
            )
            MedicalEntry.objects.using(db_alias).filter(pk=entry.pk).update(
                cumulative_amount_yen=running_by_person_year[key],
            )


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_medicalentry_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalVisit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("record_year", models.PositiveSmallIntegerField()),
                ("visited_on", models.DateField()),
                ("hospital_name", models.CharField(blank=True, max_length=150)),
                ("cumulative_amount_yen", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="medical_visits", to="ledger.person")),
            ],
            options={"ordering": ["-visited_on", "-created_at", "-id"]},
        ),
        migrations.AddField(
            model_name="medicalentry",
            name="visit",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="entries", to="ledger.medicalvisit"),
        ),
        migrations.RunPython(group_existing_medical_entries, migrations.RunPython.noop),
    ]
