# Generated by Django 5.2.17 on 2026-08-26
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0003_medicalvisit_medicalentry_visit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentsource",
            name="kind",
            field=models.CharField(
                choices=[
                    ("credit_card", "クレジットカード"), ("code_payment", "コード決済"),
                    ("point", "ポイント"), ("bank", "銀行"), ("cash", "現金・その他"),
                    ("transit", "交通系"), ("flea_market", "フリマ"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FleaMarketTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transacted_on", models.DateField()),
                ("transaction_type", models.CharField(choices=[("profit", "利益"), ("withdrawal", "出金")], max_length=20)),
                ("amount_yen", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("payment_source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="flea_market_transactions", to="ledger.paymentsource")),
            ],
            options={"ordering": ["-transacted_on", "-created_at", "-id"]},
        ),
    ]
