# Generated by Django 5.2.17 on 2026-08-30 04:29

import django.db.models.deletion
from django.db import migrations, models


def backfill_settlement_snapshots(apps, schema_editor):
    """Use only relationships already stored on each historical entry.

    In particular, do not follow a card's *current* bank setting when old
    entries never captured that second step.
    """
    PaymentSource = apps.get_model("ledger", "PaymentSource")
    HouseholdEntry = apps.get_model("ledger", "HouseholdEntry")
    for entry in HouseholdEntry.objects.select_related("payment_source", "linked_source").all().iterator():
        source = entry.payment_source
        if entry.linked_source_id:
            final = entry.linked_source
            path = " → ".join(filter(None, [entry.payment_source_name_snapshot, entry.linked_source_name_snapshot]))
        elif source.kind == "code_payment":
            final = None
            path = f"{entry.payment_source_name_snapshot} → 未設定"
        else:
            final = source
            path = entry.payment_source_name_snapshot
        HouseholdEntry.objects.filter(pk=entry.pk).update(
            settlement_source=final,
            settlement_source_name_snapshot=final.name if final else "",
            settlement_path_snapshot=path,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_householdentry_entry_type_replace_flea_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdentry',
            name='settlement_path_snapshot',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='householdentry',
            name='settlement_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settled_entries', to='ledger.paymentsource'),
        ),
        migrations.AddField(
            model_name='householdentry',
            name='settlement_source_name_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(backfill_settlement_snapshots, migrations.RunPython.noop),
    ]
