# Generated by Django 5.2.17 on 2026-09-03 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_correct_unlinked_credit_settlements'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsource',
            name='closing_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='paymentsource',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsource',
            name='main_color',
            field=models.CharField(default='#1456A0', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'カラーは#RRGGBB形式で入力してください。')]),
        ),
        migrations.AddField(
            model_name='paymentsource',
            name='payment_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='paymentsource',
            name='payment_month_offset',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '当月'), (1, '翌月'), (2, '翌々月')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
